//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAM.Infrastructure.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetIssue
    {
        public int AssetIssueId { get; set; }
        public string IssueDescription { get; set; }
        public int AssetId { get; set; }
        public string RaisedBy { get; set; }
        public System.DateTime DateRaised { get; set; }
        public AssetIssueStatus Status { get; set; }
        public string Comment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Asset Asset { get; set; }
    }
}
