//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAM.Infrastructure.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetSuggestion
    {
        public int AssetSuggestionId { get; set; }
        public string SuggestedAssetUrl { get; set; }
        public string Description { get; set; }
        public System.DateTime DateSuggested { get; set; }
        public AssetSuggestionStatus Status { get; set; }
        public string SuggestedBy { get; set; }
        public string Comment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
