//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAM.Infrastructure.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metadata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Metadata()
        {
            this.AssetMetadatas = new HashSet<AssetMetadata>();
            this.AssetTypeSupportedMetadatas = new HashSet<AssetTypeSupportedMetadata>();
        }
    
        public int MetadataId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MetadataGroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetMetadata> AssetMetadatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTypeSupportedMetadata> AssetTypeSupportedMetadatas { get; set; }
        public virtual MetadataGroup MetadataGroup { get; set; }
    }
}
